name: Windows build

on: [workflow_dispatch]

env:
  BUILD_PATH: ${{github.workspace}}
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_ROOT: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\vcpkg"

jobs:
  test:
    name: windows vcpkg
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
      script: |
         core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
         core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Compile LLVM
      shell: cmd
      run: |
        vcpkg.exe install --triplet x64-windows-release --overlay-triplets=%GITHUB_WORKSPACE%/cmake/vcpkg_triplets --x-install-root=%BUILD_PATH%/release-win/vcpkg_installed

    - name: Build AdaptiveCpp
      shell: cmd
      run: |
        cmake.exe --preset release-win
        cmake.exe --build --preset default --target package
